#spring.application.name=management
spring:
  security:
    user:
      name: user
      password: admin123
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    ignoreMigrationPatterns: '*:ignored'
    url: jdbc:sqlserver://localhost:1433;databaseName=CSDL_QL_JAVA1;encrypt=false;trustServerCertificate=true;username=user1;password=156314;
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CSDL_QL_JAVA1;encrypt=false;trustServerCertificate=true;username=user1;password=156314;
#    username: user1
#    password: 156314
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    properties:
      enable_lazy_load_no_trans: true
      format_sql: false
    open-in-view: false
  servlet:
#    path: /api
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000
  devtools:
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
server:
  port: 9001
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg